name: CI-Build
on:
    pull_request:
        branches:
            - 'develop'
    workflow_dispatch:
jobs:
    CI-Build:
        runs-on: self-hosted
        steps:
            - name: Support long file names
              run: git config --global core.longpaths true
            - uses: actions/checkout@v4
            - name: Run script with parameters
              run: |
                cd Code
                echo "Reading parameters from file..."
                Get-Content GithubRepos.txt | ForEach-Object {
                Write-Host "Running script with parameter: $_"
                python Interface.py $_
                }
              shell: powershell
            - name: Search for Result.txt and commit if found
              run: |
                files=$(find . -type f -name "Result.txt")
                if [ -n "$files" ]; then
                  echo "Found Result.txt files:"
                  echo "$files"
                  git add $files
                  git commit -m "Add all Result.txt files"
                  git push
                else
                  echo "No Result.txt files found"
                fi
              shell: powershell
