name: CI-Build

on:
    pull_request:
        branches:
            - 'develop'

    workflow_dispatch:

jobs:
    CI-Build:
        runs-on: self-hosted
        steps:
            - name: Support long file names
              run: git config --global core.longpaths true
            - uses: actions/checkout@v4
            - name: Run script with parameters
              run: |
                cd Code
                echo "Reading parameters from file..."
                Get-Content GithubRepos.txt | ForEach-Object {
                Write-Host "Running script with parameter: $_"
                python Interface.py $_
                }
              shell: pwsh
