name: CI-Build

on:
  pull_request:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  CI-Build:
    runs-on: self-hosted
    steps:
      - name: Support long file names
        run: git config --global core.longpaths true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script with parameters
        run: |
          cd Code
          echo "Reading parameters from file..."
          Get-Content GithubRepos.txt | ForEach-Object {
            Write-Host "Running script with parameter: $_"
            py Interface.py $_
          }
        shell: powershell

      - name: Search for Result.txt and commit if found
        run: |
          cd $env:GITHUB_WORKSPACE
          $files = Get-ChildItem -Path . -Filter "result.txt" -Recurse
          if ($files) {
            Write-Host "Found result.txt files:"
            $files | ForEach-Object { Write-Host $_.FullName }

            $destination = "$env:GITHUB_WORKSPACE/Code/Result"
            if (!(Test-Path -Path $destination)) {
              New-Item -ItemType Directory -Path $destination
            }

            $files | ForEach-Object { 
              $repoName = $_.FullName -replace '^.*Code\\([^\\]+)\\.*$', '$1'
              $newFileName = "result_$repoName.txt"
              Copy-Item -Path $_.FullName -Destination "$destination\$newFileName" 
            }
            Write-Host "Copied result.txt files to $destination"
          } else {
            Write-Host "No result.txt files found"
          }
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add Code/Result
          git commit -m "Add all result.txt files"
          git push 
        shell: powershell
