name: Run analize

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Create-Results:
    runs-on: self-hosted
    steps:
      - name: Support long file names
        run: git config --global core.longpaths true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install influxdb-client
        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run script with parameters
        run: |
          cd Code
          echo "Reading parameters from file..."
          Get-Content GithubRepos.txt | ForEach-Object {
            Write-Host "Running script with parameter: $_"
            py interface_script.py $_
          }
        shell: powershell

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add Code/Result
          git commit -m "Add all result.txt and parsed_results.txt files including old versions"
          git push
        shell: powershell
