name: TEST
on:
    workflow_dispatch:
jobs:
    Test:
        runs-on: self-hosted
        steps:
            - name: Support long file names
              run: git config --global core.longpaths true
            - uses: actions/checkout@v4
            - name: Run python
              run: python --version
              shell: cmd
